version: '20.10.13'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    environment:
      - discovery.type=single-node
    ports: 
      - '9200:9200'
  kibana:
    image: 'kibana:7.9.2'
    ports:
      - '5601:5601'